name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: "2019"
      run: cargo build
    - name: Run tests
      working-directory: "2019"
      run: cargo test
